### ISSUE TITLE
Question: Is it allowed to use adapted types in @JsonbConstructor?

### ISSUE THREAD

**Issue by mkarg** [jakartaee/jaxb-api#270]
I want to deserialize JSON into a POJO. The POJO is using `@JsonbConstructor` as it does not contain any setter methods. One of the parameters currently is of type `URI`. Everything deserializes fine. 😄 

For some reason, I want to map `URI` to `X`. So I wrote a `JsonbAdapter<X, URI>` and replaced the type `URI` in my POJO by `X`. Unfortunately, the result now is: ` javax.json.bind.JsonbException: Internal error: WELD-001456: Argument resolvedBean must not be null`. 😢 

**Is it forbidden to use adapted types as constructor parameters, or is this a bug of my runtime (here: Yasson)?**

>	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.lambda$getOrCreateComponent$0(BeanManagerInstanceCreator.java:71)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.getOrCreateComponent(BeanManagerInstanceCreator.java:66)
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:296)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:243)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:238)
	at org.eclipse.yasson.internal.model.CreatorModel.<init>(CreatorModel.java:55)
	at org.eclipse.yasson.internal.AnnotationIntrospector.createJsonbCreator(AnnotationIntrospector.java:198)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getCreator(AnnotationIntrospector.java:159)
	at org.eclipse.yasson.internal.AnnotationIntrospector.introspectCustomization(AnnotationIntrospector.java:737)
	at org.eclipse.yasson.internal.MappingContext.lambda$createParseClassModelFunction$1(MappingContext.java:91)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:81)
	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:60)
	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:99)

**Comment by lukasj** [comment]
Isn’t this for jsob-api instead?

**Comment by mkarg** [comment]
> Isn’t this for jsonb-api instead?

Lukas, you are right. Had several tabs open, posted into the wrong one. Silly me!
