### ISSUE TITLE
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by vaukai** [jakartaee/jaxb-api#303]
On Gentoo with `openjdk:21` we get the following errors:
Downstream bug report of other slot is https://bugs.gentoo.org/916476.
```
There were 72 failures:
1) testClassSM[0](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
2) testClassesSM[0](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
3) testPathSM[0](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
4) testClassSM[1](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
5) testClassesSM[1](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
6) testPathSM[1](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
7) testClassSM[2](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
8) testClassesSM[2](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
9) testPathSM[2](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
10) testClassSM[3](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
11) testClassesSM[3](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
12) testPathSM[3](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
13) testClassSM[4](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
14) testClassesSM[4](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
15) testPathSM[4](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
16) testClassSM[5](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
17) testClassesSM[5](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
18) testPathSM[5](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
19) testClassSM[6](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
20) testClassesSM[6](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
21) testPathSM[6](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
22) testClassSM[7](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
23) testClassesSM[7](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
24) testPathSM[7](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
25) testClassSM[8](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
26) testClassesSM[8](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
27) testPathSM[8](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
28) testClassSM[9](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
29) testClassesSM[9](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
30) testPathSM[9](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
31) testClassSM[10](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
32) testClassesSM[10](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
33) testPathSM[10](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
34) testClassSM[11](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
35) testClassesSM[11](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
36) testPathSM[11](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
37) testClassSM[12](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
38) testClassesSM[12](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
39) testPathSM[12](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
40) testClassSM[13](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
41) testClassesSM[13](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
42) testPathSM[13](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
43) testClassSM[14](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
44) testClassesSM[14](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
45) testPathSM[14](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
46) testClassSM[15](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
47) testClassesSM[15](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
48) testPathSM[15](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
49) testClassSM[16](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
50) testClassesSM[16](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
51) testPathSM[16](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
52) testClassSM[17](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
53) testClassesSM[17](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
54) testPathSM[17](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
55) testClassSM[18](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
56) testClassesSM[18](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
57) testPathSM[18](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
58) testClassSM[19](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
59) testClassesSM[19](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
60) testPathSM[19](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
61) testClassSM[20](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
62) testClassesSM[20](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
63) testPathSM[20](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
64) testClassSM[21](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
65) testClassesSM[21](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
66) testPathSM[21](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
67) testClassSM[22](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
68) testClassesSM[22](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
69) testPathSM[22](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)
70) testClassSM[23](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassSM(JAXBContextTest.java:254)
71) testClassesSM[23](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testClassesSM(JAXBContextTest.java:260)
72) testPathSM[23](jakarta.xml.bind.test.JAXBContextTest)
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at jakarta.xml.bind.test.JAXBContextTest.enableSM(JAXBContextTest.java:268)
	at jakarta.xml.bind.test.JAXBContextTest.testPathSM(JAXBContextTest.java:248)

FAILURES!!!
Tests run: 148,  Failures: 72
```

**Comment by antoniosanct** [comment]
@vaukai @lukasj 
Comment line 262 and the tests will be ok, but I don't know what is the main reason to maintain this at JDK 21.
Regards,
Antonio.

**Comment by vaukai** [comment]
> Comment line 262 [...]

https://github.com/jakartaee/jaxb-api/blob/4.0.2/jaxb-api-test/src/test/java/jakarta/xml/bind/test/JAXBContextTest.java#L262 ?

**Comment by antoniosanct** [comment]
@vaukai 
Sorry, I wrote this line because of #292 is a different line code. In your case, is L268 (in JDK21 is not possible to create a new SecurityManager). Comment this line, #292 CICD runs fine and I think that master and 4.0.2 run fine too.

Regards,
Antonio.

**Comment by laurentschoelens** [comment]
This could be closed I guess @lukasj since #349 is done now
