### ISSUE TITLE
How to unmarshall a XML without namespace using the Jakarta XML Unmarshaller?

### ISSUE THREAD

**Issue by Aravinda93** [jakartaee/jaxb-api#304]
I am trying to unmarshal an XML into a Java object using the `jakarta.xml.bind.Unmarshaller` but my XML does not contain some of the default namespaces as they are part of the XSD already. How to either explicitly mention to `Unmarshaller` to ignore these default namespaces or add them to the `XMLStreamReader` at the runtime so Unmarshaller can use them?

Following is the XML which fails to unmarshal to Java object:
```
<foo>
 <bar>Hello</bar>
</foo>
```

If I change to this then it would work as expected:
```
<foo xmlns="http://tempuri.org/">
 <bar>Hello</bar>
</foo>
```

I looked at a few examples on [StackOverflow][1] but the provided approach does not work. I do not wish to use an additional library such as Sax rather I want to handler at the XMLStreamReader level or by using the Unmarshaller. 

How to achieve this?

Following is the method for doing the unmarshalling of XML:

Main.class:
```
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Unmarshaller;

import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamReader;
import java.io.InputStream;

public class Main {
    public static void main(String[] args) throws XMLStreamException, JAXBException {
        final XMLInputFactory inputFactory = XMLInputFactory.newInstance();
        inputFactory.setProperty(XMLInputFactory.SUPPORT_DTD, Boolean.FALSE);
        inputFactory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, Boolean.FALSE);
        final InputStream inputStream = Main.class.getResourceAsStream("/SampleXML.xml");
        final XMLStreamReader xmlStreamReader = inputFactory.createXMLStreamReader(inputStream);
        final JAXBContext jaxbContext = JAXBContext.newInstance("io.convert.test", Thread.currentThread().getContextClassLoader());
        final Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();
        xmlStreamReader.next();

        while (xmlStreamReader.hasNext()) {
            Object event = unmarshaller.unmarshal(xmlStreamReader, Foo.class).getValue();
            System.out.println(event.toString());
        }
    }
}
```

Foo.class:
```

import jakarta.xml.bind.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "foo")
@XmlType(
        name = "Foo",
        propOrder = {
                "bar",
                "anyElements"
        },
        factoryClass = ObjectFactory.class,
        factoryMethod = "createFoo")
@ToString(callSuper = true)
public class Foo {
    private String bar;
    
    @XmlAnyElement(lax = true)
    private List<Object> anyElements;
}
```

ObjectFactory.class:
```
import jakarta.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public final class ObjectFactory {
  private ObjectFactory() {}
  public static Foo createFoo() {
    return new Foo();
  }
}
```

An error occurred when XML used without namespace:
```
Exception in thread "main" jakarta.xml.bind.UnmarshalException
 - with linked exception:
[Exception [EclipseLink-25004] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document
Internal Exception: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[3,15]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#ElementPrefixUnbound?test&test:one]
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.handleXMLMarshalException(JAXBUnmarshaller.java:1132)
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:471)
	at io.convert.test.Main.main(Main.java:24)
Caused by: Exception [EclipseLink-25004] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document

```

  [1]: https://stackoverflow.com/a/24387115/7584240

**Comment by antoniosanct** [comment]
@Aravinda93 
You must create a package-info.java on io.convert.test package to set elementformdefault (unset by default) to unqualified
```java
@XmlSchema(elementFormDefault = XmlNsForm.UNQUALIFIED)
package io.convert.test;

import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
```
If you don't inform this attribute, JAXB always expects qualified namespace to unmarshall execution.

Regards,
Antonio.

**Comment by Aravinda93** [comment]
@antoniosanct 

Thanks a lot for the response. I tried the approach you suggested but still getting the following error:

```
jakarta.xml.bind.UnmarshalException
 - with linked exception:
[Exception [EclipseLink-25004] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document
Internal Exception: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[3,15]
Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#ElementPrefixUnbound?test&test:on
```

I have added your `package-info.java` in the same package as the other class, but still getting the error. Following is my project structure:

<img width="266" alt="Screenshot 2024-03-05 at 10 32 44" src="https://github.com/jakartaee/jaxb-api/assets/29374160/b7780536-18c2-42bd-a840-58f5af027c13">
e]

I am not using the `NamespaceIgnoringXMLStreamReader` class since I have added the package-info.java:
```
@XmlSchema(elementFormDefault = XmlNsForm.UNQUALIFIED)
package io.convert.test;

import jakarta.xml.bind.annotation.XmlNsForm;
import jakarta.xml.bind.annotation.XmlSchema;
```

Following is my main class:
```
public class Main {
    public static void main(String[] args) throws XMLStreamException, JAXBException {
        final XMLInputFactory inputFactory = XMLInputFactory.newInstance();
        final InputStream inputStream = Main.class.getResourceAsStream("/SampleXML.xml");
        final XMLStreamReader xmlStreamReader = inputFactory.createXMLStreamReader(inputStream);
        final JAXBContext jaxbContext = JAXBContext.newInstance("io.openepcis.convert.test", Thread.currentThread().getContextClassLoader());
        final Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

        xmlStreamReader.next();
        try {
            while (xmlStreamReader.hasNext()) {
                Object event = unmarshaller.unmarshal(xmlStreamReader);
                if (event instanceof Foo foo) {
                    System.out.println(foo);
                }
            }
        } catch (UnmarshalException e) {
            e.printStackTrace();
        }
    }
}
```

@antoniosanct Can you please let me know if I need to change anything to make the unmarshaling work?

**Comment by antoniosanct** [comment]
@Aravinda93 
I don't have these error using JDK 21 and jaxb-ri master branch. Maybe some dependency are conflicting in your project and avoids that unmarshalling process works fine. I'm only using this deps:
```xml
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>4.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<version>4.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>4.0.5-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.30</version>
		</dependency>
```
![imagen](https://github.com/jakartaee/jaxb-api/assets/5426719/5648f5a7-15cb-47ef-9db6-32fb3541bfe7)

![imagen](https://github.com/jakartaee/jaxb-api/assets/5426719/1a03c2b4-2d78-416b-a291-1d5f9f5d895c)

Regards,
Antonio

**Comment by Aravinda93** [comment]
@antoniosanct Thanks there were some dependency problem it works now.
